kind: pipeline
name: default

steps:
  - name: Test
    image: gugod/perl-testbox:5.28
    commands:
      - cpanm --quiet --installdeps .
      - cpanm --quiet -n Test2::Harness
      - yath --qvf

  - name: Build
    image: gugod/perl-testbox:5.28
    depends_on:
      - Test
    commands:
      - cpanm --quiet -n Dist::Milla
      - dzil authordeps --missing | cpanm --quiet -n
      - milla build
      - ls -l

  - &installation
    name: Install (perl 5.30)
    image: perl:5.30
    depends_on:
      - Build
    commands:
      - echo *.tar.gz
      - cpanm -q *.tar.gz

  - << : *installation
    name: Install (perl 5.28)
    image: perl:5.28
